

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/identity-service
#    username: "{cipher}b7dc75d2e381a4d7c30582260105ea4c2a9d10cab711d92ddffa8a9962ff6e79"
#    password: "{cipher}b7dc75d2e381a4d7c30582260105ea4c2a9d10cab711d92ddffa8a9962ff6e79"
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.sql
