

#server:
#  port: 9095
spring:
  config:
    import: optional:configserver:http://localhost:8088
  application:
    name: API-GATEWAY-SERVICE
#  cloud:
#    gateway:
#      routes:
#        - id: room-reservation-service
#          uri: http://localhost:9090
#          predicates:
#            - Path=/roomReservations/**
