FROM openjdk:17 as builder

WORKDIR /project
ADD . /project
ADD ./etc /root

RUN ./mvnw package


FROM openjdk:17-jdk-slim
WORKDIR /app
#copy jar from builder to another stage

COPY --from=builder /project/target/config-server-0.0.1-SNAPSHOT.jar /app
#ADD target/eureka-server-0.0.1-SNAPSHOT.jar /app


CMD ["java", "-jar" , "config-server-0.0.1-SNAPSHOT.jar"]
