spring:
  application:
    name: room-service

  # Config Server import
  config:
    import: optional:configserver:http://localhost:8088 # through direct config server
  #    import: optional:configserver:http://localhost:9095/config-server # through api gateway

  # cloud:
  #   config:
  #     enabled: false
