INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO , COST)
VALUES ('Piccadilly', 'P1', '1Q' , 100 );
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Piccadilly', 'P2', '1Q' , 50 );
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Piccadilly', 'P3', '1Q', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Piccadilly', 'P4', '2D', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Piccadilly', 'P5', '2D', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Piccadilly', 'P6', '2D', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Cambridge', 'C1', '1K', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Cambridge', 'C2', '1K', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Cambridge', 'C3', '1K', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Westminster', 'W1', '1K', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Westminster', 'W2', '1K', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Westminster', 'W3', '1K', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Westminster', 'W4', '1K', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Westminster', 'W5', '2D', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Westminster', 'W6', '2D', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Westminster', 'W7', '2D', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Oxford', 'O1', '1K', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Oxford', 'O2', '1K', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Oxford', 'O3', '1Q', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Oxford', 'O4', '1Q', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Oxford', 'O5', '1Q', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Victoria', 'V1', '1K', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Victoria', 'V2', '2D', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Victoria', 'V3', '2D', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Manchester', 'M1', '1K', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Manchester', 'M2', '1K', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Manchester', 'M3', '1K', 50);
INSERT INTO ROOMS (NAME, ROOM_NUMBER, BED_INFO, COST)
VALUES ('Manchester', 'M4', '1K', 50);