FROM openjdk:17 as builder

WORKDIR /project
ADD . /project
RUN ./mvnw package


FROM openjdk:17-jdk-slim
WORKDIR /app
#copy jar from builder to another stage

COPY --from=builder /project/target/guest-service-0.0.1-SNAPSHOT.jar /app
#ADD target/eureka-server-0.0.1-SNAPSHOT.jar /app

CMD ["java", "-jar" , "guest-service-0.0.1-SNAPSHOT.jar"]
