CREATE TABLE  IF NOT EXISTS PAYMENT
(
    PAYMENT_ID      SERIAL  PRIMARY KEY,
    RESERVATION_ID    BIGINT NOT NULL,
    MODE VARCHAR(20),
    AMOUNT       numeric,
    STATUS       VARCHAR(32)
    );
