spring:
  application:
    name: guest-service

  jpa:
    hibernate:
      ddl-auto: none

  # Config Server import
  config:
    import: optional:configserver:http://localhost:8088 # through direct config server
#    import: optional:configserver:http://localhost:9095/config-server # through api gateway
