spring:
  application:
    name: reservation-service

  jpa:
    hibernate:
      ddl-auto: none

  # Config Server import
  config:
    import: optional:configserver:http://localhost:9095/config-server
