-- liquibase formatted sql

-- changeset author:1
CREATE TABLE users (
                         user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         username VARCHAR(100) UNIQUE NOT NULL,
                         password VARCHAR(255) NOT NULL,
                         role VARCHAR(50) NOT NULL DEFAULT 'ROLE_USER',
                         enabled BOOLEAN DEFAULT TRUE,
                         full_name_en VARCHAR(200) NOT NULL,
                         full_name_ar VARCHAR(200) NOT NULL,
                         email VARCHAR(150) UNIQUE NOT NULL,
                         telephone VARCHAR(30),
                         address VARCHAR(255),
                         last_login_at TIMESTAMP,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- changeset author:4
-- Insert sample users (passwords should be encoded with BCrypt in real apps)
INSERT INTO users (username, password, role, full_name_en, full_name_ar, email, telephone, address)
VALUES
    ('ali', '{noop}password', 'ROLE_USER', 'Ali Hassan', 'علي حسن', 'ali@example.com', '+966512345678', 'Riyadh, Saudi Arabia'),
    ('sara', '{noop}password', 'ROLE_USER', 'Sara Ahmed', 'سارة أحمد', 'sara@example.com', '+966511223344', 'Jeddah, Saudi Arabia'),
    ('admin', '{noop}admin123', 'ROLE_ADMIN', 'System Admin', 'مدير النظام', 'admin@example.com', '+966500000000', 'HQ');
