spring:
  application:
    name: AuthServer_KC
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/marey
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081



jwt:
  auth:
    converter:
      resource-id: mareyApp
      principle-attribute: preferred_username

#      swagger config
springdoc:
  swagger-ui:
    oauth:
      client-id: mareyApp
      client-secret: 3iu7h4YhaBVvO4LyOLaLQSbwh1SZOzEP

