spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahmedmar3y2017/configServer.git
          clone-on-start: true
        default-label: main

    bus:
      enabled: true
    stream:
      kafka:
        binder:
          auto-add-partitions: true
#    refresh:
#      additional-property-sources-to-retain:
  kafka:
    bootstrap-servers: localhost:19092 , localhost:19093 , localhost:19094

server:
  port: 8088
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#      *** auto refresh config
management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: MySecretEncryptKey123   # for demo only, keep strong & secure in prod

