spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahmedmar3y2017/configServer.git
          clone-on-start: true
        default-label: main

server:
  port: 8088
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#      *** auto refresh config
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

encrypt:
  key: MySecretEncryptKey123   # for demo only, keep strong & secure in prod

