spring:
  application:
    name: room-reservation-service
#  cloud:
#    config:
#      enabled: false
#  cloud:
#    openfeign:
#      circuitbreaker:
#        enabled: true
  config:
    import: optional:configserver:http://localhost:8088 # through direct config server
#    import: optional:configserver:http://localhost:9095/config-server # through api gateway


